# Server
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/codeplay
spring.data.mongodb.database=codeplay

# Clerk JWT Configuration
clerk.jwt.issuer=https://neutral-termite-33.clerk.accounts.dev/.well-known/jwks.json
clerk.publishable-key=pk_test_bmV1dHJhbC10ZXJtaXRlLTMzLmNsZXJrLmFjY291bnRzLmRldiQ
clerk.secret-key=sk_test_3fqDiKPjcOwdZFm9IilIyH6X1V0Ccank9euR4ZzICs

# CORS
cors.allowed-origins=http://localhost:3000

# Logging
logging.level.com.codeplay=DEBUG
